"""add chunk_index

Revision ID: 1e418ecd4471
Revises: 82a79c7662b3
Create Date: 2026-04-24 15:44:36.538022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e418ecd4471'
down_revision: Union[str, Sequence[str], None] = '82a79c7662b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chunks_chunk_index'), 'chunks', ['chunk_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_chunk_index'), table_name='chunks')
    op.drop_column('chunks', 'chunk_index')
    # ### end Alembic commands ###
