"""create core tables

Revision ID: 82a79c7662b3
Revises: 
Create Date: 2025-09-21 14:34:13.212241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82a79c7662b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'url', 'email', 'audio', name='sourcetype'), nullable=False),
    sa.Column('media_type', sa.Enum('pdf', 'image', 'audio', 'text', name='mediatype'), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('meta_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.Enum('text', 'image', name='modality'), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('content_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bbox', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_embedding_key'), 'chunks', ['embedding_key'], unique=False)
    op.create_index(op.f('ix_chunks_modality'), 'chunks', ['modality'], unique=False)
    op.create_index(op.f('ix_chunks_page'), 'chunks', ['page'], unique=False)
    op.create_table('kv_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_type', sa.Enum('date', 'number', 'text', name='valuetype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('origin', sa.Enum('docvqa', 'table', 'regex', 'llm', name='origin'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kv_extractions_confidence'), 'kv_extractions', ['confidence'], unique=False)
    op.create_index(op.f('ix_kv_extractions_document_id'), 'kv_extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_kv_extractions_key'), 'kv_extractions', ['key'], unique=False)
    op.create_index(op.f('ix_kv_extractions_value'), 'kv_extractions', ['value'], unique=False)
    op.create_index(op.f('ix_kv_extractions_value_type'), 'kv_extractions', ['value_type'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('open', 'done', 'archived', name='taskstatus'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_document_id'), 'tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_document_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_kv_extractions_value_type'), table_name='kv_extractions')
    op.drop_index(op.f('ix_kv_extractions_value'), table_name='kv_extractions')
    op.drop_index(op.f('ix_kv_extractions_key'), table_name='kv_extractions')
    op.drop_index(op.f('ix_kv_extractions_document_id'), table_name='kv_extractions')
    op.drop_index(op.f('ix_kv_extractions_confidence'), table_name='kv_extractions')
    op.drop_table('kv_extractions')
    op.drop_index(op.f('ix_chunks_page'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_modality'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_embedding_key'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
